name: Build AzureLinux Pi Image

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-image:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Create and activate venv
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run make_image.py
        run: |
          source venv/bin/activate
          python3 tools/make_image.py

      - name: Upload azl-pi.img.zst to release
        if: github.event_name == 'release' || startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: azl-pi.img.zst
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}