name: Build AzureLinux Pi Image

on:
  push:

jobs:
  build-image:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Create and activate venv
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run make_image.py
        run: |
          source venv/bin/activate
          sudo python3 tools/make_image.py
          ls -lh *xz
