name: Build AzureLinux Pi Image

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-image:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create and activate venv
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run make_image.py
        run: |
          source venv/bin/activate
          python3 tools/make_image.py

      - name: Get tag name
        run: echo "RELEASE_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Rename file with tag
        run: |
          mv azl-pi.img.zst azl-pi-${RELEASE_TAG}.img.zst

      - name: Upload azl-pi-${RELEASE_TAG}.img.zst to release
        if: github.event_name == 'release' || startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: azl-pi-${RELEASE-TAG}.img.zst
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
